import math

def true_riemann_trend(n):
    """
    Finds the theoretical baseline position of the n-th Riemann zero.
    Solves the Riemann-von Mangoldt formula using the Newton-Raphson method.
    """
    if n <= 1:
        return 14.1347  # Exact location baseline for the 1st Riemann zero
        
    # Initial guess using the standard first-order asymptotic approximation
    y = n / math.log(n)
    
    # Solve n = y * ln(y) - y iteratively (where y = t / 2pi)
    for _ in range(15):
        f = y * math.log(y) - y - n
        df = math.log(y)
        if df == 0:
            break
        y_next = y - f / df
        if abs(y_next - y) < 1e-9:
            y = y_next
            break
        y = y_next
        
    return 2 * math.pi * y

def train_pure_python_model(indices, actual_zeros):
    """
    Calculates a linear correction line (slope and intercept) 
    using pure Python Least Squares Regression formulas.
    """
    # 1. Compute the structural residuals (Reality - Math Trend)
    residuals = []
    for idx, actual in zip(indices, actual_zeros):
        trend = true_riemann_trend(idx)
        residuals.append(actual - trend)
        
    # 2. Linear Regression formulas from scratch: y = (slope * x) + intercept
    count = len(indices)
    sum_x = sum(indices)
    sum_y = sum(residuals)
    sum_xx = sum(x * x for x in indices)
    sum_xy = sum(x * y for x, y in zip(indices, residuals))
    
    # Calculate Slope and Intercept
    denominator = (count * sum_xx) - (sum_x ** 2)
    if denominator == 0:
        slope = 0.0
        intercept = sum_y / count
    else:
        slope = ((count * sum_xy) - (sum_x * sum_y)) / denominator
        intercept = ((sum_xx * sum_y) - (sum_x * sum_xy)) / denominator
        
    return slope, intercept

def predict_pure_python(future_indices, slope, intercept):
    """
    Predicts any future Riemann zero index cleanly without library scaling limits.
    """
    predictions = []
    for idx in future_indices:
        # Calculate the immutable global baseline trend
        global_trend = true_riemann_trend(idx)
        
        # Calculate the locally-trained trend offset correction
        local_correction = (slope * idx) + intercept
        
        # Combine layers
        predictions.append(global_trend + local_correction)
        
    return predictions

# ==========================================
# 📊 TEST PIPELINE (PURE PYTHON)
# ==========================================
# Simulating the data arrays generated by your custom Riemann-Siegel bisection loop
c_train = list(range(1, 55))  # Indices 1 through 54

# Mock data tracking the correct asymptotic scaling rate
g_train = [true_riemann_trend(idx) + (math.sin(idx) * 0.1) for idx in c_train]

# Train the model entirely from scratch
slope, intercept = train_pure_python_model(c_train, g_train)

# Define target indices WAY far out into the future (e.g., 500th to 504th zeros)
future_targets = [(10)+1, (10**50)+2, (10**50)+3, (10**50)+4, (10**50)+5]

# Run predictions
predictions = predict_pure_python(future_targets, slope, intercept)

print("--- Pure Python Long-Range Predictions ---")
for idx, pred in zip(future_targets, predictions):
    print(f"Predicted distant zero: {pred:.4f}")
